### ISSUE TITLE
Agrarian Skies doesnt start

### ISSUE THREAD

**Issue by diamnom** [Gamocosm/Gamocosm#42]
It's been stuck on
Status: Downloading and installing Minecraft (Agrarian Skies (1.6.4), estimated 1 minute) 
for a while now.

Any ideas? Should I just wait?

**Comment by Skyshayde** [comment]
I'm having the exact same issue with vanilla.  I'm going to assume it is global.

**Comment by DrSLDR** [comment]
My guess would be that there is some issue in querying the created server? I manage to restart an existing server I have from Gamocosm (as in, it creates the droplet and loads the image), but Gamocosm doesn't acknowledge it, so I have to start/stop Minecraft manually using SSH.

**Comment by Raekye** [comment]
Looking into it

**Comment by Raekye** [comment]
Shouldn't have taken so long, unfortunately got sick shortly after posting that >.< seems like the background worker died. Things should be fixed now, sorry for the troubles! Please let me know if you still see problems

**Comment by DrSLDR** [comment]
Glad to hear you've health again!

I've tried to fire up one of my servers again and I'm seeing partial success. The following messages are repeatedly appearing in the server log:
```
2016 Jan 22 (07:05:24 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API error: HTTP response code 401, {"status"=>"no_auth"}
2016 Jan 22 (07:05:24 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API error: HTTP response code 401, {"status"=>"no_auth"}
[Repetitions omitted]
2016 Jan 22 (07:03:07 PST) app/workers/start_minecraft_worker.rb:23:in `perform'
Error starting Minecraft on server: MCSW API error: HTTP response code 401, {"status"=>"no_auth"}
```
The last message only appeared once and points to a different line in the code. The effect seems to be that the droplet is created and the correct admin screen loads (I'm assuming because SSH works again), but I can't start/stop/backup the Minecraft server from the interface.

**Comment by Raekye** [comment]
Yeah hmmm I started noticing that too, I'm looking into it, and will post an update hopefully soon!

On a side note, agrarian skies (and I've noticed other versions of modded minecraft) seem to require java 7. I've added a wiki page for using java 7 (since 8 is installed by default)

**Comment by Raekye** [comment]
I realized the errors I was seeing should be different than the ones you have; what I was seeing I was just confusing myself with the Digital Ocean connectivity errors you'd get if you destroy and create servers too close together; tldr I've actually not seen that error before :S

I was able to start and use an existing server of mine, so I don't think it's a global problem

Would you mind posting your server name so I can search for it?
Also, if you know how to SSH, could you check the contents of `/opt/gamocosm/mcsw-auth.txt`?
There should be two lines; the first should be "gamocosm-mothership" and the second line should be some gibberish.
If you don't mind posting the first half of the second line that'd be great

**Comment by diamnom** [comment]
i recreated an agrarian server.
now im getting this error:
Error getting Minecraft properties: MCSW API network exception: execution expired

**Comment by diamnom** [comment]
how do I ssh the file?

**Comment by DrSLDR** [comment]
@Raekye Got it. The server's name is "gravelpit" if you want to take a closer look at it. It's currently on and I'll leave it on for a few hours so you can check.

`/opt/gamocosm/mcsw-auth.txt` contains a hash and this is the first half of that: `b6f223326bb0b70a`. If you don't mind me asking, what is this hash, and what is the second half?

**Comment by Raekye** [comment]
@DrSLDR For some reason the value the server had was different. I've honestly never seen it happen before, and can't imagine how it came to be. Regardless, I think I've manually fixed and tested it (seems to work for me), let me know if it's better now. Thanks for your patience!

@diamnom, here's the wiki page on SSH https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH
Though it may seem complicated if you're doing it for the first time, it's actually very powerful once you learn it (you basically have full control over the computer!)
If you're looking for a quick setup, might be faster to give me the name of the server and leave it on for a bit and I"ll do it for you xD

**Comment by diamnom** [comment]
I made a new one, its called 'agrdiamnom'

I'll look into SSH, but I'd appreciate it if you could tweak it up to work. I'm also hoping to set online_mode to false.

**Comment by Raekye** [comment]
Should be working now, let me know if it works! And I set online mode to false ;)

**Comment by diamnom** [comment]
nope, still doesnt work
new error message tho, now Im getting

Internal Exception: java.io.IOException: Connection reset by peer

**Comment by Raekye** [comment]
Looking at the logs on the server, I see "You don't have FML installed, you cannot connect to this server" and "Outdated client!". I checked the ports and all I *believe* the server setup is working correctly (could be wrong), might be an issue on the client side?

**Comment by diamnom** [comment]
yep,I'm working on it now...
trying to find an appropriate client that will work

thanks based raekye

**Comment by Raekye** [comment]
No worries, I thanks for your patience xD You're using their launcher right? From http://www.feed-the-beast.com Then it should be under 3rd party packs

**Comment by diamnom** [comment]
works
